// Copyright (c) 2022 Jonathan Lang

//---------- -------------------------- -------
//---------- !!! AUTOGENERATED CONTENT !!! -------
//---------- -------------------------- -------

//Runtime Monitoring
//File generated: 2025-01-16 18:15:54Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT_8FU7FLZIUXAL1DT3FTC8
{
    //Value Processor Method Definitions

    [UnityEngine.Scripting.PreserveAttribute]
    [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]
    private static void AOT()
    {
        //  [Field Definitions] 

        // BackendSocket::packets_per_second (System.Int32)
        // BackendWebrequests::roads_count (System.Int32)
        // BackendWebrequests::prefabs_count (System.Int32)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Int32>();

        // BackendSocket::connection_status (System.String)
        // CameraHandler::state (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_operatingSystem (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_operatingSystemFamily (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceModel (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceName (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorFrequency (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorCount (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_systemMemory (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsDeviceName (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsDeviceType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsMemorySize (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsMultiThreaded (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_batteryLevel (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_batteryStatus (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_dataPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_persistentDataPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_consoleLogPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_streamingAssetsPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_temporaryCachePath (System.String)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Object>();

        // BackendWebrequests::next_check (System.Single)
        // Baracuda.Monitoring.Modules.FPSMonitor::_fps (System.Single)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Single>();

        // PlayerTruck::position (UnityEngine.Vector3)
        // PlayerTruck::rotation (UnityEngine.Vector3)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, UnityEngine.Vector3>();

        //  [Property Definitions] 

        // Baracuda.Monitoring.Modules.FPSMonitor::TargetFrameRate (System.Int32)
        // Baracuda.Monitoring.Modules.FPSMonitor::Vsync (System.Int32)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Int32>();

        // Baracuda.Monitoring.Modules.ConsoleMonitor::Console (System.Collections.Generic.Queue<System.String>)
        // Baracuda.Monitoring.Modules.ConsoleMonitor::LastLogStacktrace (System.String)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Object>();

        //  [Collection Definitions] 

        // System.Collections.Generic.Queue<System.String>
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefEnumerable<System.Object>();
    }
}

#endif //ENABLE_IL2CPP && !DISABLE_MONITORING

//----------------------------------------------------------------------------------------------------------------------

//--- Stats ---

//General

//Monitored Member:               33
//Monitored Member Instance:      33

//MemberInfo

//Monitored Fields:               29
//Monitored Fields Instance:      29
//Monitored Properties:            4
//Monitored Properties Instance:   4

//Monitored Types

//Monitored float:                 2
//Monitored int:                   5
//Monitored Queue<string>:         1
//Monitored string:               23
//Monitored Vector3:               2

//----------------------------------------------------------------------------------------------------------------------

//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring